### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by ccgjosh** [FlagshipWP/compass#30]
What kind of hoops would I have to jump through to replace genericons with font-awesome? God forbid genericon add the vine logo....

**Comment by robneu** [comment]
It seems like Genericons is a bit of a dead project, so I'm considering making this switch. Does anyone else have any opinions one way or the other on the subject? 

My only hesitation is that Genericons are used by Jetpack and Font Awesome is kind of a huge file to include in addition to Genericons on any site that also uses Jetpack...

**Comment by RRWD** [comment]
If you use JetPack, will the Genericons fonts be loaded twice? 
Maybe load the icons with a add_theme_support, so the developer can choose Font Awesome and/or Genericons?
Font Awesome has so much choice, really like it.

**Comment by robneu** [comment]
Right now, if you use Jetpack, Genericons is only loaded once because both the version in Jetpack and the version in our theme use the same script handle. If we switch to Font Awesome, then we'll be loading both Font Awesome and Genericons for anyone who uses Jetpack. It's probably not really a huge deal.

Having an option for both feels like bloat to me. They're fairly easy to swap out, it's really just a matter of which one is the best to be used as the starting point so that most people can just use it as-is.

**Comment by RRWD** [comment]
I avoid using JetPack, feel like it slows down sites tremendously, so adding another font library might not be noticeable.

**Comment by robneu** [comment]
Haha that's a good point! I'm not a huge fan of Jetpack either... although they've done a lot to improve it recently I still try to avoid it as much as possible.

**Comment by liamness** [comment]
https://github.com/sapegin/grunt-webfont
https://github.com/google/material-design-icons

Could add a watch to a folder for some SVGs (material design icon set is a good start), then people can chop and change as they see fit. Icon fonts sets can be pretty hefty, I think it's generally better to generate your own rather than pull one in that may have many icons you don't need.

**Comment by GaryJones** [comment]
@liamness Thanks for sharing those links.

**Comment by robneu** [comment]
+1 I like this idea better than forcing people into one icon font library over another.
