### ISSUE TITLE
check text domain task inconsistent

### ISSUE THREAD

**Issue by thatryan** [FlagshipWP/compass#42]
After running `grunt newtheme` and then `grunt check` several text domain issues arise. Specifically in the 

`Running "checktextdomain:files" (checktextdomain) task` 

where an error is shown for incorrect text domain used, 

`Incorrect text domain used ("compass")`

**Comment by robneu** [comment]
I see what the issue is here. The textdomain is being replaced before the build process pulls in the dependencies via composer. I'll see about changing the ordering of some things to get this fixed up.

**Comment by thatryan** [comment]
Sweet, thank you sir!

**Comment by robneu** [comment]
I added a note about this on the [Wiki page for creating a new theme](https://github.com/FlagshipWP/compass/wiki/Create-A-New-Theme-With-Compass). As far as I can tell, this is expected behavior because Grunt reads the existing package theme.`textdomain` value before the replace task is run and then uses the old `textdomain` even though it's been replaced by the replace task.

The easiest way to solve this is to just manually update the `textdomain` to match the new `name` when you're setting up your new theme.
