### ISSUE TITLE
Use of wpcss in build tasks

### ISSUE THREAD

**Issue by RajeebTheGreat** [FlagshipWP/compass#54]
```
		'build:css': [
			'build:dependencies:css',
			'newer:sass',
			'newer:usebanner',
			'newer:autoprefixer',
			'newer:wpcss',
			'newer:cssjanus',
			'newer:cssmin',
			'newer:replace:style',
			'newer:copy:css'
		],
```
I'm unable to understand how this line of code is working in compass theme. When build:css task is done in grunt, it will call wpcss but I'm unable to find wpcss in the config files.

I'm new to grunt. Hope these questions are not irritating ones!

Any help will be appreciated.

**Comment by robneu** [comment]
Hey Rajeeb,

We used to have wpcss loaded directly in the config, but on the latest version we've offloaded all reusable elements of the config to an independent library. The wpcss config file is here: https://github.com/FlagshipWP/flagship-wp-theme-config/blob/master/config/grunt/wpcss.js

The remaining config files that are included within the theme are ones that are likely to be changed from theme-to-theme. For example we've kept the copy config in the theme because it's used to copy and concatenate JavaScript files and libraries pulled in using Bower.

**Comment by RajeebTheGreat** [comment]
Thanks for the quick reply! 

One more question:
I'm thinking of developing themes with Compass. But the thing is the Compass is getting new features and commit in regular basis. Suppose, if I pick the theme at this point and start customizing  for my own theme, how to make sure that my theme will be getting those updates from Compass? 

How you handle this situation at FlagshipWP? Any help or procedure explanation will be helpful.

Since I'm already familiar with Hybrid Core framework, this theme with useful tools like grunt, sass etc. is boon for me. Thanks again for developing and making the Compass theme open-source.

**Comment by robneu** [comment]
Well, the current version of Compass should be relatively stable. Prior to the 2.0.0 release, we were still figuring out a lot of things during the process of building themes using Compass. To be honest, the 1.0.0 branch probably should have been a beta, but that wasn't really evident until after building a few themes with it.

That aside, you should think of Compass as an alternative to Underscores. The concept is the same; it just gets you closer to a finished theme than you would be if you started from the Underscores base. New features and updates to Compass don't necessarily need to be merged into your theme, although they could be either manually or by cherry picking git commits from the Compass repo. I try to keep the majority of my commits very small and specific to make doing this easier.

Other changes such as improvements and updates to the grunt config can be pulled into your theme automatically by bumping the version number in your package.json file to the latest version of our config and loader. The same can be done for other libraries we use like the Flagship Library, Hybrid Core, and The Theme Hook Alliance because they're managed with Composer.

I hope that clarifies things a bit. If you have any other questions, please feel free to post them.

**Comment by RajeebTheGreat** [comment]
Thanks for the clarification! I just joined the Compass Community Forum. I'll post more questions there.
